name: rick_and_morty
description: Rick and Morty.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.19.0-229.0.dev <3.0.0"

dependencies:
  auto_route: ^5.0.1
  blur: ^3.1.0
  cached_network_image: ^3.2.2
  cupertino_icons: ^1.0.2
  dio: ^4.0.6
  firebase_auth: ^4.1.0
  firebase_core: ^2.1.1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  flutter_launcher_icons: ^0.10.0
  font_awesome_flutter: ^10.2.1
  freezed: ^2.1.1
  freezed_annotation: ^2.1.0
  google_fonts: ^3.0.1
  google_sign_in: ^5.4.2
  image_picker: ^0.8.5+3
  json_annotation: ^4.7.0
  path: ^1.8.2
  path_provider: ^2.0.11
  provider: ^6.0.4
  shared_preferences: ^2.0.15
  splashscreen: ^1.3.5

dev_dependencies:
  auto_route_generator: ^5.0.3
  build_runner: ^2.2.1
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  json_serializable: ^6.4.0
  flutter_native_splash: ^2.2.13
flutter_native_splash:
color: '#06121E'
image: 'assets/images/splash.png'
image_dark: 'assets/images/splash.png'
android: true
ios: true
flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/
    - assets/images/avatar.png
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
